### ISSUE TITLE
Wikipedia URLs for concepts?

### ISSUE THREAD

**Issue by sosuperic** [marvl-challenge/marvl-data#1]
Would it be possible to release the wikipedia URL's associated with each concept?

Thanks for making this dataset!

**Comment by hardyqr** [comment]
Hi, it is very easy to reverse engineer the links with the provided concept list (https://marvl-challenge.github.io/docs/hierarchy/concepts/). For example, for the concept "Agama Konghucu", you can prepend the Wikipedia address of the language, which is "https://id.wikipedia.org/wiki/" for Indonesian then add the concept name but replacing space with "_". Then you get the link of the concept: "https://id.wikipedia.org/wiki/Agama_Konghucu". It's the same for all languages.

**Comment by sosuperic** [comment]
Ah got it! That's easy, thanks so much.
